### ISSUE TITLE
Connect to node/mongodb server

### ISSUE THREAD

**Issue by HacAtac** [HacAtac/GTX-Mobile-Detailing#1]
USER STORY:
As this will be a full stack app, need to utilize node server and mongodb server

Acceptance Criteria:
As a dev I'd like to use JavaScript with node for express and mongoDB for database
So that I can create a fully functional back-end for app

**Comment by HacAtac** [comment]
Hey guys, I've completed this step. We're set up on mongoDB server as-well as node server.
Let me know if you have any questions. 

(I HAVENT SET  UP CONCURRENTLY YET)

**Comment by HacAtac** [comment]
FYI I did make one model 'services' and have seeded the data. I was looking at his website and it needed to be structured a certain way. Let me know what y'all think.

**Comment by KumiYAM** [comment]
In original main, there were no package.json file for ROOT. Please make sure we all have same set up of node.

**Comment by HacAtac** [comment]
Good job team, we've also added an apollo server here
