### ISSUE TITLE
Authorization JWTs

### ISSUE THREAD

**Issue by rvanooyen** [HacAtac/GTX-Mobile-Detailing#14]

**Comment by rvanooyen** [comment]
User Story:

As a user, I want to authorize users to access the website with JWTs.

Acceptance Criteria:

As a user
When I log in as a user, I am authenticated as an authorized user.

**Comment by HacAtac** [comment]
Thus far we have JWT set up for user login. Do we need to implement JWTs anywhere else guys?

**Comment by HacAtac** [comment]
Have implemented the JWT so that we can conditionaly render certain data, stuff on our application. Going to move this to review then done.
