### ISSUE TITLE
Inside Schema resolvers.js

### ISSUE THREAD

**Issue by HacAtac** [HacAtac/GTX-Mobile-Detailing#4]
USER STORY:
As Devs, when we see our schema folder we should see resolvers.js , inside file we should see logic/CRUD methods to execute our Queries and Mutations.

Acceptance Criteria:
When we see our resolvers.js
Then we see that were using mongoose crud methods to 'route'  our Queries and Mutations
Also we will need to make an index.js file to require our typeDefs/resolvers files then export them.

**Comment by KumiYAM** [comment]
Basic version resolvers.js is ready to push.  now I am waiting for approval of latest merge develop to main. So that I can refresh other files update.

**Comment by HacAtac** [comment]
We need to finish resolvers for as follows:
3: Updating service
<---------------------------------------------------------------------------------------------------------->
USER
1: May need to revisit getting a user so that we can display whose logged in etc..
2: Also get all users.

**Comment by HacAtac** [comment]
Create, read, update, delete resolvers are now completed using mongoose ODM methods. Moving this over to QA
